services:
  tailscaled:
    image: tailscale/tailscale
    restart: unless-stopped
    #privileged: true
    cap_add:
      - net_admin
      - net_raw
      - sys_module
    command: "tailscaled --state=mem:"
    #environment:
    #  - AUTHKEY=tskey-...
    volumes:
      - /dev/net/tun:/dev/net/tun
